# Generated by Django 3.0.3 on 2020-03-01 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='world_premiere',
            field=models.DateField(default=datetime.date(2020, 3, 1), verbose_name='World premiere'),
        ),
    ]
